backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "home" # Used in routes, e.g., /admin/collections/blog
    label: "Home Page" # Used in the UI
    folder: "pages/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "home" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Hero Title", name: "heroTitle", widget: "string"}
      - {label: "Hero Subtitle", name: "heroSubtitle", widget: "string"}
      - {label: "Hero Link Url", name: "heroLinkUrl", widget: "string"}
      - {label: "Hero Link Text", name: "heroLinkText", widget: "string"}
      - {label: "Our Mission Title", name: "ourMissionTitle", widget: "string"}
      - {label: "Our Mission Overview", name: "ourMissionOverview", widget: "text"}
      - {label: "Our Work Title", name: "ourWorkTitle", widget: "string"}
      - {label: "Our Work Overview", name: "ourWorkOverview", widget: "text"}
      - {label: "The Need Section Title", name: "theNeedTitle", widget: "string"}
      - {label: "The Need Section Subtitle", name: "theNeedSubtitle", widget: "string"}
      - label: "The Need Section Content"
        name: "theNeedContent"
        widget: "list"
        fields:
          - label: "Content Row"
            name: theNeedRow
            widget: object
            fields:
              - {label: "Image", name: image, widget: "image"}
              - {label: "Text", name: text1, widget: "text"}
              - {label: "Big Orange Statistics", name: orangeStats, widget: "string"}
              - {label: "Text", name: text2, widget: "text"}
      - {label: "Donate Section Title", name: "donateTitle", widget: "string"}
      - {label: "Donate Section Subtitle", name: "donateSubtitle", widget: "string"}
      - {label: "Donate Section Text", name: "donateText", widget: "text"}
      - label: "Donate Primary Button"
        name: "donatePrimaryButton"
        widget: "object"
        fields:
          - {label: "Button Text", name: buttonText, widget: "string"}
          - {label: "URL", name: buttonUrl, widget: "string"}
      - label: "Donate Secondary Button"
        name: "donateSecondaryButton"
        widget: "object"
        fields:
          - {label: "Button Text", name: buttonText, widget: "string"}
          - {label: "URL", name: buttonUrl, widget: "string"}
      - {label: "Donate Background Image", name: "donateImage", widget: "image"}
      - {label: "Contact Us Title", name: "contactUsTitle", widget: "string"}
      - {label: "Contact Us Text", name: "contactUsText", widget: "text"}
      - label: "Testimonial Slider: Enter up to four testimonials"
        name: "testimonialSlider"
        widget: "list"
        fields:
          - label: "Testimonial"
            name: testimonial
            widget: object
            fields:
              - {label: "Quote", name: quote, widget: "text"}
              - {label: "Attribution", name: attribution, widget: "text"}
              

        

           
       



      
              



